export const columns: Record<string, string> = {
  date: "Дата",
  number_milking: "Дойка",
  total_cows: "Всего коров",
  total_weight_kg: "Надой",
  start_time: "Начало доения",
  milking_duration: "Продолж.",
  cows_per_hour: "Коров в час",
  total_reattaches: "Повторные соединения",
  percent_reattaches: "% повторные соединения",
  percent_justified_reattach: "% оправданных переподкл.",
  percent_increasing_flow: "% возр. молокопотока",
  average_low_flow: "Секунд в слабом потоке",
  percent_low_flow: "% секунд в слабом потоке",
  milk_two_min: "Молоко за 2 минуты",
  percent_two_min_milk: "% молока за 2 минуты",
  average_duration: "Время на 1 корову",
  total_manual_detach: "Руч. откл.",
  percent_manual_detach: "% руч.откл.",
  total_manual_mode: "Ручные режимы",
  percent_manual_mode: "% ручных режимов",
  percent_no_milk: "Не присвоено молока",
  mixed_up_cows: "Путанные коровы",
};
